name: CI Pipeline

on:
  push:
    # branches: [ phase-3-laying-the-base ]
  pull_request:
    # branches: [ phase-3-laying-the-base ]
env:
  senseBoxIds : ${{ vars.senseBoxIds}}
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest pytest-asyncio pytest-cov

    - name: Lint Python code
      run:  python -m pylint --exit-zero --disable=W0613,W0611,R,C app/ tests/
        
    # - name: Lint Dockerfile
    #   uses: hadolint/hadolint-action@v2.1.0
    #   with:
    #         dockerfile: Dockerfile

    - name: Lint Dockerfile (GitHub)
      if: ${{ !env.ACT }}
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: ./Dockerfile

    - name: Lint Dockerfile (Local ACT)
      if: ${{ env.ACT }}
      run: |
        docker run --rm -v $PWD:/app -w /app hadolint/hadolint hadolint Dockerfile
        

    - name: Run PyTest For Unit Tests
      uses: pavelzw/pytest-action@v2.2.0
      with:
        emoji: false
        verbose: false
        job-summary: false
        test-files: tests/
        test-args: -v -m "unit" 

    - name: Run PyTest For Integration Tests
      uses: pavelzw/pytest-action@v2.2.0
      with:
        emoji: false
        verbose: false
        job-summary: false
        test-files: tests/
        test-args: -v -m "integration" 


    - name: Build Docker image
      run: |
        docker build -t hivebox:${{ github.sha }} .
        docker images
